package:
  name: wakari-app-viewer
  version: 1.2.1

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - flask
    - werkzeug
    - ipython-we
    - pygments
    - pandoc

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1

# optional Python entry points
  entry_points:
    - wk-viewer = wkviewer.server:main

about:
  home: https://github.com/ContinuumIO/wakari-app-viewer
  license: MIT License
