package:
  name: wakari-app-viewer
  version: 1.0.0

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  entry_points:
    - wk-app-viewer = wkviewer.server:main

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - flask
    - werkzeug
    - ipython-we
    - pygments
    - pandoc

about:
  home: https://github.com/ContinuumIO/wakari-app-viewer
  license: MIT License
