package:
  name: wk-viewer    
  version: 1.1.0

requirements:
  build:
    - python
    - distribute
 
  run:
    - python
    - flask
    - werkzeug
    - ipython-we

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1

# optional Python entry points
  entry_points:
    - wk-viewer = wkviewer.server:main

about:
  home: https://github.com/ContinuumIO/wakari-viewer-app
  license: MIT License
